<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>DVLD_Buisness</RootNamespace>
    <AssemblyName>DVLD_Buisness</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DVLD_DataAccess\DVLD_DataAccess.csproj" />
  </ItemGroup>

</Project>